### ISSUE TITLE
API概览建议增加到接口的超链接

### ISSUE THREAD

**Issue by cici-2019** [huaweicloudDocs/vpc#4]
建议参照ECS（https://support.huaweicloud.com/api-ecs/ecs_01_0008.html），划分为VPC接口说明和原生OpenStack接口说明两个section，并增加到对应类型的超链接。
VPC接口列表中缺少查询网络IP使用情况、虚拟IP接口的类型。

**Comment by helly4169** [comment]
直接用华为云API Explorer可以看到了：
https://apiexplorer.developer.huaweicloud.com/apiexplorer/doc?product=VPC&api=NeutronCreateSecurityGroup

**Comment by MeetZY001** [comment]
已补充
