### ISSUE TITLE
创建同一帐户下的对等连接，缺少界面截图

### ISSUE THREAD

**Issue by Jorgensen** [huaweicloudDocs/vpc#5]
https://github.com/huaweicloudDocs/vpc/blob/master/cn.zh-cn/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/%E5%88%9B%E5%BB%BA%E5%90%8C%E4%B8%80%E5%B8%90%E6%88%B7%E4%B8%8B%E7%9A%84%E5%AF%B9%E7%AD%89%E8%BF%9E%E6%8E%A5.md

添加VPC对等连接路由（路由表已解耦）部分，缺少界面截图

**Comment by MeetZY001** [comment]
已补充
