### ISSUE TITLE
补充无法删除默认安全组的说明

### ISSUE THREAD

**Issue by Jorgensen** [huaweicloudDocs/vpc#6]
https://github.com/huaweicloudDocs/vpc/blob/master/cn.zh-cn/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97/%E9%BB%98%E8%AE%A4%E5%AE%89%E5%85%A8%E7%BB%84%E5%92%8C%E8%A7%84%E5%88%99.md

没有说明默认安全组无法删除，需要补充无法删除默认安全组的说明

**Comment by MeetZY001** [comment]
已有说明：您无法删除默认安全组，但可以修改默认安全组的规则。

**Comment by MeetZY001** [comment]
已有说明：您无法删除默认安全组，但可以修改默认安全组的规则。
