### ISSUE TITLE
申请共享带宽章节操作场景内容建议补充优化

### ISSUE THREAD

**Issue by fighting-go-go-go** [huaweicloudDocs/vpc#9]
当前操作场景只有一句描述“共享带宽需要申请才能使用。”，建议补充优化，比如具体说明客户在哪些场景下可以申请，申请后产生的效果如何等。建议从前面概述章节提取总结内容放到这边来。

**Comment by MeetZY001** [comment]
补充说明：
客户有大量业务在云上时，如果每个实例单独使用一条带宽，则需要较多的带宽实例，并且总的带宽费用会较高。您可以通过申请共享带宽，将多个EIP加入共享带宽，实现所有实例共用一条带宽，从而节省企业的网络运营成本，同时方便运维统计。
